'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PemiluVoteApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan
        '''.
        '''</summary>
        Friend ReadOnly Property _1csv() As String
            Get
                Return ResourceManager.GetString("_1csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _1rst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1rst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan.
        '''</summary>
        Friend ReadOnly Property _2csv() As String
            Get
                Return ResourceManager.GetString("_2csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _2rst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_2rst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan.
        '''</summary>
        Friend ReadOnly Property _3csv() As String
            Get
                Return ResourceManager.GetString("_3csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _3rst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_3rst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan.
        '''</summary>
        Friend ReadOnly Property _4csv() As String
            Get
                Return ResourceManager.GetString("_4csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _4rst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_4rst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan.
        '''</summary>
        Friend ReadOnly Property _5csv() As String
            Get
                Return ResourceManager.GetString("_5csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _5rst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_5rst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _nothing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_nothing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jam,NIPM,Nama,Kelas/Jabatan,Pilihan.
        '''</summary>
        Friend ReadOnly Property masterdata() As String
            Get
                Return ResourceManager.GetString("masterdata", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
